name: VITE-BPMN-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 步骤名
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # 执行npm脚本打包项目
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 发布到个人仓库
      - name: Deploy Step One
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.VITE_BPMN_TOKEN }}
          BRANCH: master
          FOLDER: dist
          REPOSITORY_NAME: miyuesc/miyuesc.github.io
          TARGET_FOLDER: vite-vue-bpmn-process

      # 发布到团队仓库
      - name: Deploy Step Two
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.VITE_BPMN_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
